# Numpy Exercises 2

In [1]:
import numpy as np

import matplotlib.pyplot as plt
import random # Thư viện built-in của Python 

**Question 1**

Search for the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as `True`. First time occurrences should be `False` \
Input: `[0 0 3 0 2 4 2 2 2 2]` \
Correct Output: `[False  True False  True False False  True  True  True  True]`

In [10]:
#Init array
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)
# TODO
mask = np.full_like(a, True, dtype=bool)
# The numpy.unique function with return_index=True returns a tuple containing two arrays. The first array contains the unique elements of the input array a, and the second array contains the indices of the first occurrences of these unique elements in the original array.
first_occurrences = np.unique(a, return_index=True)[1]
mask[first_occurrences] = False
mask

Array:  [0 0 3 0 2 4 2 2 2 2]


array([False,  True, False,  True, False, False,  True,  True,  True,
        True])

**Question 2**

Return all items in array `a` that not in array `b` \
Input: \
`a` = `[1,2,3,4,5]` \
`b` = `[5,6,7,8,9]` \
Output: \
`[1,2,3,4]`

In [80]:
a = np.random.choice(range(10), 7, replace=False)
b = np.random.choice(range(10), 7, replace=False)
print(a,b)
#TODO
# in1d returns True if the element of a is in b, otherwise False
mask = np.in1d(a, b)
a[~mask]

[6 0 2 3 7 5 9] [9 1 4 0 2 6 5]


array([3, 7])

**Question 3**

Given a vector `a`, build a new vector with 2 consecutive zeros interleaved between each value. \
Input: \
`a` = `[4, 3, 4, 9, 8]` \
Output: \
`[4. 0. 0. 3. 0. 0. 4. 0. 0. 9. 0. 0. 8.]`

In [41]:
a = np.random.randint(1, 10, 5)
print(a)
#TODO
new_shape = a.shape[0] + (a.shape[0] - 1)*2
result = np.zeros(new_shape, dtype=int)
result[::3] = a
result

[4 7 2 5 4]


array([4, 0, 0, 7, 0, 0, 2, 0, 0, 5, 0, 0, 4])

---
*For the next few questions we will work with `Iris Dataset`*

In [70]:
iris_1d = np.genfromtxt('Data/Iris.csv', delimiter=',', skip_header=1, dtype=None,encoding=None)
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

**Question 4**\
Filter the rows of iris_2d that has `petallength` (3rd column) > 1.5 and `sepallength` (1st column) < 5.0

In [50]:
#TODO
mask = (iris_2d[:, 0] < 5 ) & (iris_2d[:, 2] > 1.5)
iris_2d[mask]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

**Question 5**\
Add a new text column to `iris_2d`, which based on the petal length (3rd) column, such that if petal length is: \
- `Less than 3` --> 'small'
- `3-5` --> 'medium'
- `>=5` --> 'large'

In [60]:
#TODO
new_col = np.full(len(iris_2d), 'medium')
new_col[iris_2d[:, 2] < 3] = 'small'
new_col[iris_2d[:, 2] >= 5] = 'large'
iris_2d = np.hstack((iris_2d, new_col.reshape(-1, 1)))
iris_2d

array([['5.1', '3.5', '1.4', '0.2', 'small'],
       ['4.9', '3.0', '1.4', '0.2', 'small'],
       ['4.7', '3.2', '1.3', '0.2', 'small'],
       ['4.6', '3.1', '1.5', '0.2', 'small'],
       ['5.0', '3.6', '1.4', '0.2', 'small'],
       ['5.4', '3.9', '1.7', '0.4', 'small'],
       ['4.6', '3.4', '1.4', '0.3', 'small'],
       ['5.0', '3.4', '1.5', '0.2', 'small'],
       ['4.4', '2.9', '1.4', '0.2', 'small'],
       ['4.9', '3.1', '1.5', '0.1', 'small'],
       ['5.4', '3.7', '1.5', '0.2', 'small'],
       ['4.8', '3.4', '1.6', '0.2', 'small'],
       ['4.8', '3.0', '1.4', '0.1', 'small'],
       ['4.3', '3.0', '1.1', '0.1', 'small'],
       ['5.8', '4.0', '1.2', '0.2', 'small'],
       ['5.7', '4.4', '1.5', '0.4', 'small'],
       ['5.4', '3.9', '1.3', '0.4', 'small'],
       ['5.1', '3.5', '1.4', '0.3', 'small'],
       ['5.7', '3.8', '1.7', '0.3', 'small'],
       ['5.1', '3.8', '1.5', '0.3', 'small'],
       ['5.4', '3.4', '1.7', '0.2', 'small'],
       ['5.1', '3.7', '1.5', '0.4'

**Question 6**\
Find the value of second longest `petallength` of species `setosa`

In [79]:
#TODO
species = np.array([row[-1] for row in iris_1d])
setosa_specie_rows = iris_2d[species == 'Iris-setosa']
setosa_petallengths = np.unique(setosa_specie_rows[:, 2])
setosa_petallengths[np.argsort(setosa_petallengths)[-2]]

1.7